package com.nexora.hop.platformfoundation.identityaccess.domain;

/**
 * Coarse-grained "screen access" permission baseline for the IAM permission model
 * (enterprise-product-foundation-standard.yaml {@code mandatory_foundations.iam_permission_model}).
 * <p>
 * Each value maps 1:1 to an employee-portal AppShell screen: holding the permission means the
 * user's role(s) may access that screen. This is intentionally coarse — finer per-action
 * permissions (e.g. distinguishing "view" from "edit" within a screen) are follow-up scope, not
 * covered here.
 */
public enum PermissionCode {
    SCREEN_TENANTS,
    SCREEN_LABORATORIES,
    SCREEN_BRANCHES,
    SCREEN_USERS,
    SCREEN_ROLE_ASSIGNMENTS,
    SCREEN_AUDIT_EVENTS,
    SCREEN_DIAGNOSTIC_CATALOG,
    SCREEN_PERSON_SEARCH,
    SCREEN_PATIENTS,
    SCREEN_DOCTORS,
    SCREEN_PATIENT_REGISTRATIONS,
    SCREEN_RECEPTION,
    SCREEN_DIAGNOSTIC_ORDERS,
    SCREEN_CASH_SESSIONS,
    SCREEN_SALES,
    SCREEN_BILLING_REQUESTS,
    SCREEN_SAMPLE_COLLECTION,
    SCREEN_SAMPLE_LABELING,
    SCREEN_SAMPLE_RECEPTION,
    SCREEN_LABORATORY_PROCESSING,
    SCREEN_TECHNICAL_VALIDATION,
    SCREEN_MEDICAL_VALIDATION,
    SCREEN_RESULT_RELEASE,
    SCREEN_RESULT_SEARCH,
    SCREEN_RESULT_REPORTS,
    SCREEN_CRITICAL_ESCALATIONS,
    SCREEN_RESULT_NOTIFICATIONS,
    SCREEN_INTEGRATION_ENDPOINTS,
    SCREEN_API_MANAGEMENT,
    SCREEN_MIGRATION_JOBS,
    SCREEN_INVENTORY_CATALOG,
    SCREEN_INVENTORY_REAGENTS,
    SCREEN_INVENTORY_LOTS,
    SCREEN_INVENTORY_PROCUREMENT,
    SCREEN_INVENTORY_STOCK_MOVEMENTS,
    SCREEN_INVENTORY_ADJUSTMENTS,
    SCREEN_INVENTORY_WASTE,
    SCREEN_INTERNAL_QUALITY_CONTROLS,
    SCREEN_EQUIPMENT,
    SCREEN_CALIBRATIONS,
    SCREEN_MAINTENANCE,
    PORTAL_PATIENT_PROFILE_VIEW,
    PORTAL_PATIENT_APPOINTMENTS_VIEW,
    PORTAL_PATIENT_ORDERS_VIEW,
    PORTAL_PATIENT_RESULTS_VIEW,
    PORTAL_PATIENT_NOTIFICATIONS_VIEW,
    PORTAL_DOCTOR_PATIENTS_VIEW,
    PORTAL_DOCTOR_RESULTS_VIEW,
    PORTAL_DOCTOR_ORDERS_VIEW,
    PORTAL_DOCTOR_NOTIFICATIONS_VIEW,
    PORTAL_SUPPORT_IMPERSONATE
}
