id: APP-PORT-001
name: Nexora Application Portfolio
version: 0.17.0
status: Draft
applications:
  public:
    - APP-001
  employee:
    - APP-002
  patient:
    - APP-003
    - APP-005
  doctor:
    - APP-004
    - APP-006
  externalSystems:
    - APP-007
    - APP-008
  intelligence:
    - APP-009
  analytics:
    - APP-010
qualityAttributes:
  - API Contract First
  - Centralized IAM
  - Internationalization
  - Progressive Enhancement
  - Observability
  - Accessibility
