/**
 * Result Report History screen (MVP-MOD-007-FE-001, BCM-RES-002 PDF Report Generation).
 *
 * Implements:
 *   SCR-RPT-002-01 Result Report History   (/results/{resultId}/reports)
 *   SCR-RPT-002-02 Regenerate Report       (/results/{resultId}/reports/regenerate)
 *
 * The regenerate action enforces the release-state precondition via the backend service;
 * the frontend only calls the endpoint when the result exists and shows generation status.
 */
import { useState } from "react";
import { useAdminScope } from "../../state/AdminScopeContext";
import { useAsyncAction } from "../../state/useAsyncAction";
import { ScopeIndicator } from "../common/ScopeIndicator";
import { StatusBanner } from "../common/StatusBanner";
import { listResultReports, regenerateReport } from "../../api/resultsDeliveryApi";
import { MESSAGES } from "../../i18n/messages";
import type { GeneratedResultReport } from "../../api/types";

const ACTOR_ID = "current_user";

function reportStatusClass(status: string): string {
  return `catalog-status catalog-status--${status.toLowerCase().replace(/_/g, "-")}`;
}

export function ResultReportsScreen() {
  const { scope } = useAdminScope();
  const { tenantId } = scope;

  const [resultId, setResultId] = useState("");
  const [reports, setReports] = useState<GeneratedResultReport[]>([]);

  const listAction = useAsyncAction(async () => {
    if (!resultId.trim() || !tenantId) throw new Error(MESSAGES.selectResultFirst);
    const loaded = await listResultReports(resultId.trim(), tenantId);
    setReports(loaded);
    return loaded;
  });

  const regenerateAction = useAsyncAction(async () => {
    if (!resultId.trim() || !tenantId) throw new Error(MESSAGES.selectResultFirst);
    const report = await regenerateReport(resultId.trim(), tenantId, ACTOR_ID);
    setReports((prev) => [report, ...prev]);
    return report;
  });

  async function handleLoadReports() {
    await listAction.run();
  }

  async function handleRegenerate() {
    await regenerateAction.run();
  }

  return (
    <section aria-labelledby="result-reports-heading">
      <h2 id="result-reports-heading">Result Report History</h2>
      <ScopeIndicator />
      {!tenantId && (
        <p className="status-banner status-banner--error">
          Select a tenant before viewing reports.
        </p>
      )}

      <label htmlFor="rpt-result-id">Result ID</label>
      <input
        id="rpt-result-id"
        type="text"
        value={resultId}
        onChange={(e) => setResultId(e.target.value)}
        placeholder="Enter result ID"
      />

      <button
        type="button"
        disabled={!resultId.trim() || !tenantId || listAction.status === "loading"}
        onClick={handleLoadReports}
        style={{ marginLeft: "0.5rem" }}
      >
        Load Reports
      </button>
      <StatusBanner
        status={listAction.status}
        errorMessage={listAction.errorMessage}
        successMessage="Reports loaded."
      />

      {listAction.status === "success" && reports.length === 0 ? (
        <p className="empty-state">{MESSAGES.noReportsGenerated}</p>
      ) : null}

      {reports.length > 0 ? (
        <table>
          <caption>Report History</caption>
          <thead>
            <tr>
              <th scope="col">Report ID</th>
              <th scope="col">Status</th>
              <th scope="col">Generated At</th>
              <th scope="col">Generated By</th>
              <th scope="col">Document ID</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.reportId}>
                <td>{report.reportId}</td>
                <td>
                  <span className={reportStatusClass(report.status)}>{report.status}</span>
                </td>
                <td>{report.generatedAt ? new Date(report.generatedAt).toLocaleString() : "—"}</td>
                <td>{report.generatedBy ?? "—"}</td>
                <td>{report.documentId ?? "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : null}

      <div className="panel" style={{ marginTop: "1.5rem" }}>
        <h3>Regenerate Report</h3>
        <p>
          Triggers PDF re-generation for a released result. The backend enforces the release-state
          precondition (BCM-RES-002 rule RN-001).
        </p>
        <button
          type="button"
          disabled={!resultId.trim() || !tenantId || regenerateAction.status === "loading"}
          onClick={handleRegenerate}
        >
          Regenerate Report
        </button>
        <StatusBanner
          status={regenerateAction.status}
          errorMessage={regenerateAction.errorMessage}
          successMessage={MESSAGES.reportRegenerated}
        />
      </div>
    </section>
  );
}
